-name: Setup Frontend
  hosts: all
  become: true
  tasks:
    - name: Install NGINX
      ansible.builtin.dnf:
        name: nginx
        state: installed












# component=frontend
# source common.sh

# Head "INSTALLING NGINX"
# dnf install nginx -y &>>$log_file
# echo $?

# Head "Copy Expense Config File"
# cp expense.conf /etc/nginx/default.d/expense.conf &>>$log_file
# echo $?

# App_Prereq "/usr/share/nginx/html"

# Head "STARTING NGINX SERVICE"
# systemctl enable  nginx &>>$log_file
# systemctl restart nginx &>>$log_file
# echo $?

#DIR=$1
#Head "DELETING EXITING APP CONTENT"
#rm -rf $1 &>>$log_file
#echo $?
#
#Head "CREATING APPLICATION DIRECTORY"
#mkdir $1 &>>$log_file
#echo $?
#
#Head "DOWNLOADING APPLICATION CONTENT"
#curl -o /tmp/${component}.zip https://expense-artifacts.s3.amazonaws.com/${component}.zip &>/tmp/expense.log
#echo $?
#
#cd $1
#echo $?
#
#Head "EXTRACTING APPLICATION CONTENT"
#unzip /tmp/${component}.zip &>>$log_file
#echo $?